#reference link https://github.com/ntsim/hot-spring-docker
version: '3'

services:
  db:
    image: mysql:5.5
    restart: always
    container_name: mysqlspring
    restart: unless-stopped
    tty: true
    env_file:
      - ./mysql/.env
    ports:
      - "33062:3306"
    volumes:
      - spring-volume-mysql:/var/lib/mysql/
    networks:
      - app

  app:
      build: .
      ports:
        - '80:8080'
      container_name: springbootapp
      volumes:
        - ./:/app
      working_dir: /app
      user: appuser
      depends_on:
        - db
      restart: always        
      #command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
      command: sh run.sh
      networks:
        - app

networks:
  app:
    driver: bridge

volumes:
  spring-volume-mysql:
    driver: local
